export const CAR_FETCH_REQUEST = 'CAR_FETCH_REQUEST';
export const CAR_FETCH_SUCCESS = 'CAR_FETCH_SUCCESS';
export const CAR_FETCH_FAILURE = 'CAR_FETCH_FAILURE';

export const CARS_FETCH_REQUEST = 'CARS_FETCH_REQUEST';
export const CARS_FETCH_SUCCESS = 'CARS_FETCH_SUCCESS';
export const CARS_FETCH_FAILURE = 'CARS_FETCH_FAILURE';

export const CARS_REFRESH_REQUEST = 'CARS_REFRESH_REQUEST';
export const CARS_REFRESH_SUCCESS = 'CARS_REFRESH_SUCCESS';
export const CARS_REFRESH_FAILURE = 'CARS_REFRESH_FAILURE';

export const CAR_OPTIONS_FETCH_REQUEST = 'CAR_OPTIONS_FETCH_REQUEST';
export const CAR_OPTIONS_FETCH_SUCCESS = 'CAR_OPTIONS_FETCH_SUCCESS';
export const CAR_OPTIONS_FETCH_FAILURE = 'CAR_OPTIONS_FETCH_FAILURE';

export const CAR_INITIALIZE  = 'CAR_INITIALIZE';

export const CAR_CREATE_REQUEST  = 'CAR_CREATE_REQUEST';
export const CAR_CREATE_SUCCESS  = 'CAR_CREATE_SUCCESS';
export const CAR_CREATE_FAILURE  = 'CAR_CREATE_FAILURE';

export const CAR_UPDATE_REQUEST  = 'CAR_UPDATE_REQUEST';
export const CAR_UPDATE_SUCCESS  = 'CAR_UPDATE_SUCCESS';
export const CAR_UPDATE_FAILURE  = 'CAR_UPDATE_FAILURE';

export const RIDES_FETCH_REQUEST = 'RIDES_FETCH_REQUEST';
export const RIDES_FETCH_SUCCESS = 'RIDES_FETCH_SUCCESS';
export const RIDES_FETCH_FAILURE = 'RIDES_FETCH_FAILURE';

export const RIDES_REFRESH_REQUEST = 'RIDES_REFRESH_REQUEST';
export const RIDES_REFRESH_SUCCESS = 'RIDES_REFRESH_SUCCESS';
export const RIDES_REFRESH_FAILURE = 'RIDES_REFRESH_FAILURE';

export const RIDES_SET_DEFAULT_PER = 'RIDES_SET_DEFAULT_PER';
export const RIDES_AS_PASSENGER_SET_DEFAULT_PER = 'RIDES_AS_PASSENGER_SET_DEFAULT_PER,';
export const RIDES_AS_DRIVER_SET_DEFAULT_PER = 'RIDES_AS_DRIVER_SET_DEFAULT_PER,';

export const RIDES_AS_PASSENGER_FETCH_REQUEST = 'RIDES_AS_PASSENGER_FETCH_REQUEST';
export const RIDES_AS_PASSENGER_FETCH_SUCCESS = 'RIDES_AS_PASSENGER_FETCH_SUCCESS';
export const RIDES_AS_PASSENGER_FETCH_FAILURE = 'RIDES_AS_PASSENGER_FETCH_FAILURE';

export const RIDES_AS_PASSENGER_REFRESH_REQUEST = 'RIDES_AS_PASSENGER_REFRESH_REQUEST';
export const RIDES_AS_PASSENGER_REFRESH_SUCCESS = 'RIDES_AS_PASSENGER_REFRESH_SUCCESS';
export const RIDES_AS_PASSENGER_REFRESH_FAILURE = 'RIDES_AS_PASSENGER_REFRESH_FAILURE';

export const RIDES_AS_DRIVER_FETCH_REQUEST = 'RIDES_AS_DRIVER_FETCH_REQUEST';
export const RIDES_AS_DRIVER_FETCH_SUCCESS = 'RIDES_AS_DRIVER_FETCH_SUCCESS';
export const RIDES_AS_DRIVER_FETCH_FAILURE = 'RIDES_AS_DRIVER_FETCH_FAILURE';

export const RIDES_AS_DRIVER_REFRESH_REQUEST = 'RIDES_AS_DRIVER_REFRESH_REQUEST';
export const RIDES_AS_DRIVER_REFRESH_SUCCESS = 'RIDES_AS_DRIVER_REFRESH_SUCCESS';
export const RIDES_AS_DRIVER_REFRESH_FAILURE = 'RIDES_AS_DRIVER_REFRESH_FAILURE';

export const RIDE_FILTER_UPDATE = 'RIDE_FILTER_UPDATE';
export const RIDE_FILTER_CLEAR = 'RIDE_FILTER_CLEAR';
export const RIDE_SEARCH_UPDATE = 'RIDE_SEARCH_UPDATE';
export const RIDE_SEARCH_CLEAR = 'RIDE_SEARCH_CLEAR';

export const RIDE_AS_DRIVER_FILTER_UPDATE = 'RIDE_AS_DRIVER_FILTER_UPDATE';
export const RIDE_AS_DRIVER_FILTER_CLEAR = 'RIDE_AS_DRIVER_FILTER_CLEAR';

export const RIDE_AS_PASSENGER_FILTER_UPDATE = 'RIDE_AS_PASSENGER_FILTER_UPDATE';
export const RIDE_AS_PASSENGER_FILTER_CLEAR = 'RIDE_AS_PASSENGER_FILTER_CLEAR';

export const RIDE_INITIALIZE = 'RIDE_INITIALIZE';

export const RIDE_FETCH_REQUEST = 'RIDE_FETCH_REQUEST';
export const RIDE_FETCH_SUCCESS = 'RIDE_FETCH_SUCCESS';
export const RIDE_FETCH_FAILURE = 'RIDE_FETCH_FAILURE';

export const RIDE_OPTIONS_FETCH_REQUEST = 'RIDE_OPTIONS_FETCH_REQUEST';
export const RIDE_OPTIONS_FETCH_SUCCESS = 'RIDE_OPTIONS_FETCH_SUCCESS';
export const RIDE_OPTIONS_FETCH_FAILURE = 'RIDE_OPTIONS_FETCH_FAILURE';

export const RIDE_CREATE_REQUEST = 'RIDE_CREATE_REQUEST';
export const RIDE_CREATE_SUCCESS = 'RIDE_CREATE_SUCCESS';
export const RIDE_CREATE_FAILURE = 'RIDE_CREATE_FAILURE';

export const RIDE_UPDATE_REQUEST = 'RIDE_UPDATE_REQUEST';
export const RIDE_UPDATE_SUCCESS = 'RIDE_UPDATE_SUCCESS';
export const RIDE_UPDATE_FAILURE = 'RIDE_UPDATE_FAILURE';

export const RIDE_REQUEST_CREATE_REQUEST = 'RIDE_REQUEST_CREATE_REQUEST';
export const RIDE_REQUEST_CREATE_SUCCESS = 'RIDE_REQUEST_CREATE_SUCCESS';
export const RIDE_REQUEST_CREATE_FAILURE = 'RIDE_REQUEST_CREATE_FAILURE';

export const RIDE_REQUEST_CHANGE_REQUEST = 'RIDE_REQUEST_CHANGE_REQUEST';
export const RIDE_REQUEST_CHANGE_SUCCESS = 'RIDE_REQUEST_CHANGE_SUCCESS';
export const RIDE_REQUEST_CHANGE_FAILURE = 'RIDE_REQUEST_CHANGE_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_CLEAR_ERRORS = 'LOGIN_CLEAR_ERRORS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CURRENT_USER_FETCH_REQUEST = 'CURRENT_USER_FETCH_REQUEST';
export const CURRENT_USER_FETCH_SUCCESS = 'CURRENT_USER_FETCH_SUCCESS';
export const CURRENT_USER_FETCH_FAILURE = 'CURRENT_USER_FETCH_FAILURE';

export const CURRENT_USER_CREATE_REQUEST = 'CURRENT_USER_CREATE_REQUEST';
export const CURRENT_USER_CREATE_SUCCESS = 'CURRENT_USER_CREATE_SUCCESS';
export const CURRENT_USER_CREATE_FAILURE = 'CURRENT_USER_CREATE_FAILURE';

export const CURRENT_USER_UPDATE_REQUEST = 'CURRENT_USER_UPDATE_REQUEST';
export const CURRENT_USER_UPDATE_SUCCESS = 'CURRENT_USER_UPDATE_SUCCESS';
export const CURRENT_USER_UPDATE_FAILURE = 'CURRENT_USER_UPDATE_FAILURE';

export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_FAILURE = 'USERS_FETCH_FAILURE';

export const USERS_REFRESH_REQUEST = 'USERS_REFRESH_REQUEST';
export const USERS_REFRESH_SUCCESS = 'USERS_REFRESH_SUCCESS';
export const USERS_REFRESH_FAILURE = 'USERS_REFRESH_FAILURE';

export const USER_INITIALIZE = 'USER_INITIALIZE';

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';

export const NOTIFICATIONS_FETCH_REQUEST = 'NOTIFICATIONS_FETCH_REQUEST';
export const NOTIFICATIONS_FETCH_SUCCESS = 'NOTIFICATIONS_FETCH_SUCCESS';
export const NOTIFICATIONS_FETCH_FAILURE = 'NOTIFICATIONS_FETCH_FAILURE';

export const NOTIFICATIONS_REFRESH_REQUEST = 'NOTIFICATIONS_REFRESH_REQUEST';
export const NOTIFICATIONS_REFRESH_SUCCESS = 'NOTIFICATIONS_REFRESH_SUCCESS';
export const NOTIFICATIONS_REFRESH_FAILURE = 'NOTIFICATIONS_REFRESH_FAILURE';

export const NOTIFICATION_UPDATE_REQUEST = 'NOTIFICATION_UPDATE_REQUEST';
export const NOTIFICATION_UPDATE_SUCCESS = 'NOTIFICATION_UPDATE_SUCCESS';
export const NOTIFICATION_UPDATE_FAILURE = 'NOTIFICATION_UPDATE_FAILURE';

export const NOTIFICATION_ADD_SUCCESS = 'NOTIFICATION_ADD_SUCCESS';
export const NOTIFICATION_ACTIVE_ADD = 'NOTIFICATIOD_ACTIVN_ADE';
export const NOTIFICATION_ACTIVE_REMOVE = 'NOTIFICAMOVE_ACTION_RETIVE';

export const SHOW_MODAL = 'SHOW_MODAL';
export const UPDATE_MODAL = 'UPDATE_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const RESET_SETTINGS = 'RESET_SETTINGS';
