export const RIDES_FETCH_REQUEST = 'RIDES_FETCH_REQUEST';
export const RIDES_FETCH_SUCCESS = 'RIDES_FETCH_SUCCESS';
export const RIDES_FETCH_FAILURE = 'RIDES_FETCH_FAILURE';

export const RIDE_FETCH_REQUEST = 'RIDE_FETCH_REQUEST';
export const RIDE_FETCH_SUCCESS = 'RIDE_FETCH_SUCCESS';
export const RIDE_FETCH_FAILURE = 'RIDE_FETCH_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const CURRENT_USER_FETCH_REQUEST = 'CURRENT_USER_FETCH_REQUEST';
export const CURRENT_USER_FETCH_SUCCESS = 'CURRENT_USER_FETCH_SUCCESS';
export const CURRENT_USER_FETCH_FAILURE = 'CURRENT_USER_FETCH_FAILURE';

export const CURRENT_USER_CREATE_REQUEST = 'CURRENT_USER_CREATE_REQUEST';
export const CURRENT_USER_CREATE_SUCCESS = 'CURRENT_USER_CREATE_SUCCESS';
export const CURRENT_USER_CREATE_FAILURE = 'CURRENT_USER_CREATE_FAILURE';
