export const CAR_FETCH_REQUEST = 'CAR_FETCH_REQUEST';
export const CAR_FETCH_SUCCESS = 'CAR_FETCH_SUCCESS';
export const CAR_FETCH_FAILURE = 'CAR_FETCH_FAILURE';

export const CARS_FETCH_REQUEST = 'CARS_FETCH_REQUEST';
export const CARS_FETCH_SUCCESS = 'CARS_FETCH_SUCCESS';
export const CARS_FETCH_FAILURE = 'CARS_FETCH_FAILURE';

export const CAR_OPTIONS_FETCH_REQUEST = 'CAR_OPTIONS_FETCH_REQUEST';
export const CAR_OPTIONS_FETCH_SUCCESS = 'CAR_OPTIONS_FETCH_SUCCESS';
export const CAR_OPTIONS_FETCH_FAILURE = 'CAR_OPTIONS_FETCH_FAILURE';

export const CAR_INITIALIZE  = 'CAR_INITIALIZE';

export const CAR_CREATE_REQUEST  = 'CAR_CREATE_REQUEST';
export const CAR_CREATE_SUCCESS  = 'CAR_CREATE_SUCCESS';
export const CAR_CREATE_FAILURE  = 'CAR_CREATE_FAILURE';

export const CAR_UPDATE_REQUEST  = 'CAR_UPDATE_REQUEST';
export const CAR_UPDATE_SUCCESS  = 'CAR_UPDATE_SUCCESS';
export const CAR_UPDATE_FAILURE  = 'CAR_UPDATE_FAILURE';

export const RIDES_FETCH_REQUEST = 'RIDES_FETCH_REQUEST';
export const RIDES_FETCH_SUCCESS = 'RIDES_FETCH_SUCCESS';
export const RIDES_FETCH_FAILURE = 'RIDES_FETCH_FAILURE';

export const RIDE_FETCH_REQUEST = 'RIDE_FETCH_REQUEST';
export const RIDE_FETCH_SUCCESS = 'RIDE_FETCH_SUCCESS';
export const RIDE_FETCH_FAILURE = 'RIDE_FETCH_FAILURE';

export const RIDE_OPTIONS_FETCH_REQUEST = 'RIDE_OPTIONS_FETCH_REQUEST';
export const RIDE_OPTIONS_FETCH_SUCCESS = 'RIDE_OPTIONS_FETCH_SUCCESS';
export const RIDE_OPTIONS_FETCH_FAILURE = 'RIDE_OPTIONS_FETCH_FAILURE';

export const RIDE_CREATE_REQUEST = 'RIDE_CREATE_REQUEST';
export const RIDE_CREATE_SUCCESS = 'RIDE_CREATE_SUCCESS';
export const RIDE_CREATE_FAILURE = 'RIDE_CREATE_FAILURE';

export const RIDE_UPDATE_REQUEST = 'RIDE_UPDATE_REQUEST';
export const RIDE_UPDATE_SUCCESS = 'RIDE_UPDATE_SUCCESS';
export const RIDE_UPDATE_FAILURE = 'RIDE_UPDATE_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CURRENT_USER_FETCH_REQUEST = 'CURRENT_USER_FETCH_REQUEST';
export const CURRENT_USER_FETCH_SUCCESS = 'CURRENT_USER_FETCH_SUCCESS';
export const CURRENT_USER_FETCH_FAILURE = 'CURRENT_USER_FETCH_FAILURE';

export const CURRENT_USER_CREATE_REQUEST = 'CURRENT_USER_CREATE_REQUEST';
export const CURRENT_USER_CREATE_SUCCESS = 'CURRENT_USER_CREATE_SUCCESS';
export const CURRENT_USER_CREATE_FAILURE = 'CURRENT_USER_CREATE_FAILURE';

export const CURRENT_USER_UPDATE_REQUEST = 'CURRENT_USER_UPDATE_REQUEST';
export const CURRENT_USER_UPDATE_SUCCESS = 'CURRENT_USER_UPDATE_SUCCESS';
export const CURRENT_USER_UPDATE_FAILURE = 'CURRENT_USER_UPDATE_FAILURE';
